import os
import subprocess
import time
from threading import Timer
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# --- Configuration ---
WATCH_DIR = "."
DEBOUNCE_SECONDS = 20.0
IGNORED_DIRS = {".git", "__pycache__", ".venv", "venv", "env"}
BRANCH_NAME = "main"

# Global timer for debouncing
commit_timer = None

def run_cmd(command):
    """Run a shell command and return stdout, root exit code."""
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    return result.returncode, result.stdout.strip(), result.stderr.strip()

def perform_smart_commit():
    """Analyze changes, commit, and push."""
    global commit_timer
    commit_timer = None
    
    print("\n[git_auto] Debounce timer finished. Analyzing changes...")
    
    # 1. Add all changes
    print("[git_auto] Running 'git add .'...")
    rc, out, err = run_cmd("git add .")
    if rc != 0:
        print(f"[ERROR] Failed to 'git add': {err}")
        return

    # 2. Check status using porcelain
    rc, out, err = run_cmd("git status --porcelain")
    if rc != 0:
        print(f"[ERROR] Failed to run 'git status': {err}")
        return
        
    if not out:
        print("[git_auto] No changes detected after adding (working tree clean).")
        return

    # Parse what changed
    lines = out.split("\n")
    changed_files = []
    has_py = False
    has_config = False
    first_py_file = ""

    for line in lines:
        if len(line) < 3:
            continue
        status = line[:2]
        filepath = line[3:].strip()
        changed_files.append(filepath)
        
        filename = os.path.basename(filepath)
        
        if filepath.endswith(".py"):
            has_py = True
            if not first_py_file:
                first_py_file = filename
        elif filename in ["requirements.txt", "pyproject.toml", "package.json", "pytest.ini"]:
            has_config = True

    # 3. Determine Smart Commit Message
    commit_message = "chore: update project files"
    if has_py:
        commit_message = f"refactor: update python logic in {first_py_file}"
    elif has_config:
        commit_message = "build: update dependencies or config"
        
    print(f"[git_auto] Selected commit message: '{commit_message}'")
    
    # 4. Commit
    rc, out, err = run_cmd(f'git commit -m "{commit_message}"')
    if rc != 0 and "nothing to commit" not in out:
        print(f"[ERROR] Failed to commit: {err}")
        return

    # 5. Push
    print(f"[git_auto] Pushing to origin/{BRANCH_NAME}...")
    rc, out, err = run_cmd(f"git push origin {BRANCH_NAME}")
    
    if rc == 0:
        print(f"[SUCCESS] Successfully pushed changes to {BRANCH_NAME}!")
    else:
        print(f"\n[CRITICAL ERROR] Git push failed!")
        print(f"Details: {err}")
        print("[git_auto] Stopping script to prevent infinite error loops (e.g., merge conflicts).")
        # Stopping the entire process by forcefully exiting
        os._exit(1)


class ChangeHandler(FileSystemEventHandler):
    """Handles file system events generated by watchdog."""
    
    def on_any_event(self, event):
        if event.is_directory:
            return
            
        # Ignore configured directories
        path_parts = set(event.src_path.replace("\\", "/").split("/"))
        if IGNORED_DIRS.intersection(path_parts):
            return

        print(f"[git_auto] Detected change: {event.src_path}")
        self.schedule_commit()

    def schedule_commit(self):
        """Debounce: Start or restart the 20-second timer."""
        global commit_timer
        if commit_timer is not None:
            commit_timer.cancel()
        
        commit_timer = Timer(DEBOUNCE_SECONDS, perform_smart_commit)
        commit_timer.start()
        print(f"[git_auto] Timer reset. Waiting {DEBOUNCE_SECONDS}s before committing...")


if __name__ == "__main__":
    # Ensure this is a git repository before starting
    if not os.path.isdir(".git"):
        print("[ERROR] No .git directory found. Please run this script in the root of a git repository.")
        exit(1)

    print("=========================================")
    print(f"Starting git_auto.py watchdog...")
    print(f"Directory: {os.path.abspath(WATCH_DIR)}")
    print(f"Debounce Time: {DEBOUNCE_SECONDS}s")
    print(f"Ignored Dirs: {IGNORED_DIRS}")
    print("=========================================")

    event_handler = ChangeHandler()
    observer = Observer()
    observer.schedule(event_handler, path=WATCH_DIR, recursive=True)
    observer.start()
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n[git_auto] Stopping due to KeyboardInterrupt.")
        if commit_timer:
            commit_timer.cancel()
        observer.stop()
    
    observer.join()
